// Adicione suas receitas manualmente aqui!
const receitas = [
  {
    titulo: "Bolo de Cenoura com Cobertura de Chocolate",
    imagem: "https://i.imgur.com/YFyz0Yj.jpg",
    descricao: "Um bolo fofinho e saboroso com cobertura cremosa de chocolate, perfeito para o café da tarde.",
    tempo: "45 min",
    dificuldade: "Fácil",
  },
  {
    titulo: "Lasanha à Bolonhesa",
    imagem: "https://i.imgur.com/wCk5Tuk.jpg",
    descricao: "Camadas de massa, molho bolonhesa e queijo gratinado, o verdadeiro clássico italiano.",
    tempo: "1h 10min",
    dificuldade: "Médio",
  },
  {
    titulo: "Torta de Limão",
    imagem: "https://i.imgur.com/vH2bBvJ.jpg",
    descricao: "Base crocante, recheio cremoso de limão e cobertura leve de merengue. Doce e cítrica na medida certa.",
    tempo: "50 min",
    dificuldade: "Fácil",
  },
  {
    titulo: "Strogonoff de Frango",
    imagem: "https://i.imgur.com/kffr8M7.jpg",
    descricao: "Clássico prato brasileiro com frango cremoso e um toque de ketchup e mostarda.",
    tempo: "40 min",
    dificuldade: "Fácil",
  },
  {
    titulo: "Strogonoff de Frango Avançado",
    imagem: "https://superprix.vteximg.com.br/arquivos/ids/171812-600-600/Strogonoff-de-Frango-Sadia-550g.jpg?v=636094628091630000",
    descricao: "Clássico prato brasileiro com frango cremoso e um toque de ketchup e mostarda. de forma muito avançada e difícil de se fazer.",
    tempo: "5 min",
    dificuldade: "Muito difícil",
  },
  {
    titulo: "Brownie",
    imagem: "https://jonesinfortaste.com/wp-content/uploads/2019/10/Black-Cat-Brownies-PROCESS-2.jpg",
    descricao: "Brownie de chocolate com cobertura de caramelo em um formato muito diferenciado.",
    tempo: "50 min",
    dificuldade: "Média",
  },
  {
    titulo: "Torta de Maça Nova",
    imagem: "https://cdn.urbano.com.br/uploads/ubn002-19h-segmentos-ubn-setembro-v2-culturanacozinha-1-800.jpg",
    descricao: "Torta Nova de maça muito top, boa mesmo, doce e bem cheirosa com bastante maça e bem saudável também.",
    tempo: "48 min",
    dificuldade: "Média + 2",
  },
  {
    titulo: "Torta de Maça",
    imagem: "https://cdn.urbano.com.br/uploads/ubn002-19h-segmentos-ubn-setembro-v2-culturanacozinha-1-800.jpg",
    descricao: "Torta de maça muito top, boa mesmo, doce e bem cheirosa com bastante maça e bem saudável também.",
    tempo: "38 min",
    dificuldade: "Média",
  },
  {
    titulo: "Macarrão com Salsicha",
    imagem: "https://www.sabornamesa.com.br/media/k2/items/cache/3f6926ce145b6fd2c270d507ee89d5ef_XL.jpg",
    descricao: "Espaguete com Salsicha e Creme de leite",
    tempo: "30 min",
    dificuldade: "Fácil",
  },
  {
    titulo: "Lasanha",
    imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNZnw4cf5bIv_Og-FoB3RecVCZltYQ8pz4MRI63Q4oxqeAmABLpv5ltc3YrDZ9ri9zlgq9tBrIfPZsjdkHQ7EWR_3LsHPGI_EL68OH-hnU&s=10",
    descricao: "Lasanha de carne moída com queijo",
    tempo: "1 horas",
    dificuldade: "Fácil",
  },
];
